config/routes.rb
Rails.application.routes.draw do
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  post "contact" => "home#contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :images
  # mount_uploaders :images, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.includes(:images).all
    @categories = Category.second
  end

  def contact
    customer = {name: params[:name], email: params[:email], phone: params[:phone]}
    ApplicationMailer.contact_me(params[:message], customer).deliver_now
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/_about.html.erb
<div class="about" id="about">
	<div class="container">
		<div class="about-main">
			<div class="col-md-6 about-left_w3ls_img">

			</div>
			<div class="col-md-6 about-right_w3ls">
			  <div class="about-top_agile_its">
					<h2>About Us</h2>
					<p>Dear Valued Customers,
					Greetings!</p>
					<p>We are Vavimex Company Limited. We are an expert supplier in green energy field which is located in Agricultural country Viet Nam. </p>
					<p>We have been staying here to export rice husk pellets, rice husk powder, rice husk ash, rice husk and commodities related to waste products from Agriculture. </p>
					<p>Not only that,  Our strong point would be our location being next to Mekong Delta river where the largest source of rice yield is located. We also have spacious warehouse and we have a supplier network guaranteed of stable quantity supplied, as they are the most potential rice mills in the Southern of Vietnam, and are Vietnam's biggest rice husk pellets factories. We with a pioneering spirit, will never stop learning, researching, developing and expand our supplier network in order to serve our customers to the maximum who have great demand such as ceramic tile manufacturers, calcite material manufacturers, the food processing industry in the world and heating  etc. At the same time, we always encourage and remind our manufacturers to never stop improving the quality of our products and increasing producing efficiency. We are keeping track of the supplier’s processing to always have a discipline system in processing in order to control the quality. That is the reason why we confidently believe that we have enough ability about Quality and Quantity to supply large volume of long-term stability for the above commodities. </p>
					<span>
						We believe that we deserve your trust.
						Thanks for spending time.
						Sincerely and Best Regard!
						The Vavimex Team
					</span>
			  </div>
		  </div>
	    <div class="clearfix"> </div>
    </div>
	</div>
</div>

app/views/home/_contact.html.erb
    <div class="contact-w3ls" id="contact">
  <div class="container">
    <div class="agileits_heading_section">
      <h3 class="wthree_head">Contact Us</h3>
      <p class="w3l_sub_para_agile">Give me a message</p>
    </div>
    <div class="inner_w3l_agile_grids-1">
      <div class="contact-w3-agile2" data-aos="flip-left">
        <div class="contact-agileits">
          <h4>Drop a Line</h4>
          <p class="contact-agile2">Email us for more detailed infomation</p>
          <%= form_with url: contact_path, method: "post" do |f| %>
            <div class="col-md-6 w3l_area_its">
              <div class="control-group form-group">
                <div class="controls">
                  <label class="contact-p1">Full Name:</label>
                  <%= f.text_field :name, type: "text", class: "form-control", required: true %>
                  <p class="help-block"></p>
                </div>
              </div>
              <div class="control-group form-group">
                <div class="controls">
                  <label class="contact-p1">Phone Number:</label>
                  <%= f.text_field :phone, type: "tel", class: "form-control", required: true %>
                  <p class="help-block"></p>
                </div>
              </div>
            </div>
            <div class="col-md-6 w3l_area">
              <div class="control-group form-group">
                <div class="controls">
                  <label class="contact-p1">Email Address:</label>
                  <%= f.text_field :email, type: "email", class: "form-control", required: true %>
                  <p class="help-block"></p>
                </div>
              </div>
              <div class="control-group form-group">
                <div class="controls">
                  <label class="contact-p1">Message:</label>
                  <%= f.text_area :message, rows: 3, class: "form-control" %>
                  <p class="help-block"></p>
                </div>
              </div>
              <div id="success"></div>
              <!-- For success/fail messages -->
              <%= f.button "Send", type: "submit", class: "btn btn-primary" %>
            </div>
            <div class="clearfix"> </div>
          <% end %>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>

app/views/home/_gallery.html.erb

<div class="container">
    <ul id="myTab" class="nav nav-tabs" role="tablist">
			<li role="presentation" class="active"><a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home">RICE HUSK PRODUCT</a></li>
		</ul>
    <div id="products" class="row list-group">
    	<%= render @products %>
    </div>
</div>
<style type="text/css">
.glyphicon { margin-right:5px; }
.thumbnail
{
    margin-bottom: 20px;
    padding: 0px;
    -webkit-border-radius: 0px;
    -moz-border-radius: 0px;
    border-radius: 0px;
}

.item.list-group-item
{
    float: none;
    width: 100%;
    background-color: #fff;
    margin-bottom: 10px;
}
.item.list-group-item:nth-of-type(odd):hover,.item.list-group-item:hover
{
    background: #428bca;
}

.item.list-group-item .list-group-image
{
    margin-right: 10px;
}
.item.list-group-item .thumbnail
{
    margin-bottom: 0px;
}
.item.list-group-item
{
    padding: 9px 9px 0px 9px;
}
.item.list-group-item:nth-of-type(odd)
{
    background: #eeeeee;
}

.item.list-group-item:before, .item.list-group-item:after
{
    display: table;
    content: " ";
}

.item.list-group-item img
{
    float: left;
}
.item.list-group-item:after
{
    clear: both;
}
.list-group-item-text
{
    margin: 0 0 11px;
}
.list-group-image
{
   height: 200px !important;
}
.caption {
    overflow-y: scroll;
    height: 200px;
}
</style>
<script type="text/javascript">
	$(window).on('load resize', function(){
    var win = $(this);
    if (win.width() < 514) {
		$('#products .item').addClass('list-group-item');
    } else
    {
     $('#products .item').removeClass('list-group-item');

        $('#products .item').addClass('grid-group-item');
    }

});
</script>

app/views/home/_main_product.html.erb
<div class="news">
	<div class="container">
		<h3 class="wthree_head">News</h3>
		<p class="w3l_sub_para_agile">Curabitur quis egestas diam</p>
		<div class="w3-agileits-news-grids">
			<div class="col-md-6 news-left">
				<div class="w3-agile-news-img">
					<a href="#myModal" data-toggle="modal"><%= image_tag "g1.jpg", alt: "" %></a>
					<h4><a href="#myModal" data-toggle="modal">Pellentesque habitant </a></h4>
					<p>Donec justo ante, maximus et aliquam et, elementum ac purus. Nam eget ante ac velit laoreet sodales ut vel nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="col-md-6 news-left">
				<div class="w3-agile-news-img">
					<a href="#myModal" data-toggle="modal"><%= image_tag "g2.jpg", alt: "" %></a>
					<h4><a href="#myModal" data-toggle="modal">Pellentesque habitant </a></h4>
					<p>Nam eget ante ac velit laoreet sodales ut vel nibh. Donec justo ante, maximus et aliquam et, elementum ac purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="clearfix"> </div>
		</div>
		<div class="w3-agileits-news-grids  news-w3row2">
			<div class="col-md-6 news-left">
				<div class="w3-agile-news-img">
					<a href="#myModal" data-toggle="modal"><%= image_tag "g4.jpg", alt: "" %></a>
					<h4><a href="#myModal" data-toggle="modal">Pellentesque habitant </a></h4>
					<p>Donec justo ante, maximus et aliquam et, elementum ac purus. Nam eget ante ac velit laoreet sodales ut vel nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="col-md-6 news-left">
				<div class="w3-agile-news-img">
					<a href="#myModal" data-toggle="modal"><%= image_tag "g3.jpg", alt: "" %></a>
					<h4><a href="#myModal" data-toggle="modal">Pellentesque habitant </a></h4>
					<p>Nam eget ante ac velit laoreet sodales ut vel nibh. Donec justo ante, maximus et aliquam et, elementum ac purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
</div>

app/views/home/_stat.html.erb
<div class="stats jarallax" id="stats">
  <div class="agile_overlay2">
    <div class="container">
      <div class="agileits_heading_section">
        <h3 class="wthree_head two">Stats</h3>
        <p class="w3l_sub_para_agile">For Digital Life</p>

      </div>
      <div class="inner_w3l_agile_grids-1">
        <div class="col-md-3 w3layouts_stats_left w3_counter_grid">
            <i class="fa fa-picture-o" aria-hidden="true"></i>
          <p class="counter">1,546</p>
          <h3>Sodales ut</h3>
        </div>
        <div class="col-md-3 w3layouts_stats_left w3_counter_grid1">
            <i class="fa fa-smile-o" aria-hidden="true"></i>
          <p class="counter">14,345</p>
          <h3>Donec justo</h3>
        </div>
        <div class="col-md-3 w3layouts_stats_left w3_counter_grid2">
        <i class="fa fa-trophy" aria-hidden="true"></i>
          <p class="counter">563</p>
          <h3>Velit laoreet</h3>
        </div>
        <div class="col-md-3 w3layouts_stats_left w3_counter_grid3">
        <i class="fa fa-camera" aria-hidden="true"></i>
          <p class="counter"><%= @visitor_count %></p>
          <h3>Vistor</h3>
        </div>
        <li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
          <div data-id="visitor_count" data-view="List" data-unordered="true" data-title="Visitors This Month"></div>
        </li>
        <div class="clearfix"> </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= render "about" %>
<div class="tooltip-content">
	<div class="modal fade features-modal" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title">Vavimex</h4>
				</div>
				<div class="modal-body">
					<%= image_tag "g4.jpg", class: "img-responsive", alt: "Vavimex" %>
					<h5>Fishing Season Now Open</h5>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent varius lectus vitae porttitor fringilla. Donec turpis orci, elementum a nunc quis, maximus varius ipsum. Sed bibendum ex in dignissim bibendum.</p>
				</div>
			</div>
		</div>
	</div>
</div>
<%= render "gallery" %>


<%= render "stat" %>

<%= render "contact" %>

<div class="contact-w3-agile1 map" data-aos="flip-right">
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2136.3703152252733!2d106.65263866378695!3d10.878437443608044!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTDCsDUyJzQxLjQiTiAxMDbCsDM5JzEzLjQiRQ!5e0!3m2!1sen!2s!4v1521983718821" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>

<a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
<script>
	$(document).ready(function() {1
		$('#JiSlider').JiSlider({color: '#fff', start: 3, reverse: true}).addClass('ff')
	})

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36251023-1']);
  _gaq.push(['_setDomainName', 'jqueryscript.net']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

	$('.jarallax').jarallax({
		speed: 0.5,
		imgWidth: 1366,
		imgHeight: 768
	})

	$('.counter').countUp();

	jQuery(document).ready(function($) {
		$(".scroll").click(function(event){
			event.preventDefault();
			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
		});
	});


	$(document).ready(function() {
		$().UItoTop({ easingType: 'easeOutQuart' });
	});

	$(window).load(function() {
		$("#flexiselDemo1").flexisel({
			visibleItems:1,
			animationSpeed: 1000,
			autoPlay:false,
			autoPlaySpeed: 3000,
			pauseOnHover: true,
			enableResponsiveBreakpoints: true,
			responsiveBreakpoints: {
				portrait: {
					changePoint:480,
					visibleItems: 1
				},
				landscape: {
					changePoint:640,
					visibleItems:1
				},
				tablet: {
					changePoint:768,
					visibleItems: 1
				}
			}
		});
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vavimex</title>
    <%= favicon_link_tag "favicon.ico" %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
	  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
	  <link href="//fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
	  <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>

  </head>

  <body">
    <div class="banner-top">
    	<%= render "shared/header" %>
    	<%= render "shared/banner" %>
    </div>
    <%= yield %>
    <%= render "shared/footer" %>
    <script type="text/javascript">
      <%= render "shared/ga.js" %>
    </script>
    <%= render "shared/ga" %>
    <%= content_for :specific_page_js %>
  </body>
</html>

app/views/products/_product.html.erb
<div class="item col-xs-4 col-lg-4 list-group-item">
  <div class="thumbnail">
     <%= image_tag product.images[0].name, class: "group list-group-image" %>
    <div class="caption">
      <h4 class="group inner list-group-item-heading">
        <%= product.name %>
      </h4>
      <% eval(product.description).each do |key, value| %>
        <p class="group inner list-group-item-text">
          <%=  "#{key.to_s.gsub("_", " ").capitalize}: #{value.to_s}" %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner-silder">
	<div id="JiSlider" class="jislider">
		<ul>
		<% (0..5).each do |index| %>
			<li>
				<div class="w3layouts-banner-top <%= "w3layouts-banner-top#{index}" if index > 0 %>">
						<div class="container">
							<div class="agileits-banner-info">
							</div>
						</div>
					</div>
			</li>
		<% end %>
		</ul>
	</div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
	<div class="container">
		<div class="agile_footer_copy">
			<div class="w3agile_footer_grids">
				<div class="col-md-4 w3agile_footer_grid">
					<h3>About Us</h3>
					<p>We are Vavimex Company Limited. We are an expert supplier in green energy field which is located in Agricultural country Viet Nam.<span>We have been staying here to export rice husk pellets, rice husk powder, rice husk ash, rice husk and commodities related to waste products from Agriculture..</span></p>
				</div>
				<div class="col-md-4 w3agile_footer_grid">
					<h3>Contact Info</h3>
					<ul>
						<li><i class="glyphicon glyphicon-map-marker" aria-hidden="true"></i>No 176/2, TA 16 Street, Quarter 2, Thoi An Ward, District 12.<span>Ho Chi Minh City.</span></li>
						<li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i><a href="mailto:httvan@vavimex.com">httvan@vavimex.com</a></li>
						<li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i><a href="tel:+84909597667">+84 909 59 7667</a></li>
					</ul>
				</div>
				<div class="col-md-4 w3agile_footer_grid w3agile_footer_grid1">
					<h3>Navigation</h3>
					<ul>
						<li><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span><%= link_to "Home", root_path, "data-turbolinks": false %></li>
						<li><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
							<%= link_to "Product", root_path(anchor: "products"), "data-turbolinks": false %>
						</li>
						<li><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
							<%= link_to "About", root_path(anchor: "about"), "data-turbolinks": false %>
						</li>
						<li><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
							<%= link_to "Contact", root_path(anchor: "contact"), "data-turbolinks": false %>
						</li>
					</ul>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
</div>

app/views/shared/_ga.js.erb
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-117522461-1']);
_gaq.push(['_trackPageview']);

(function() {
  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();

app/views/shared/_header.html.erb
<div class="header">
	<div class="container">
		<div class="header-left">
			<div class="agileinfo-phone">
				<p><a href="tel:+84909597667" style="color: white;"><i class="fa fa-volume-control-phone" aria-hidden="true"> +84 909 59 7667</i></a></p>
			</div>
			<div class="agileinfo-phone agileinfo-map">
				<p><a href="mailto:httvan@vavimex.com" style="color: white;"><i class="fa fa-envelope" aria-hidden="true"></i> httvan@vavimex.com</a></p>
			</div>
			<div class="search-grid">
				<form action="#" method="post">
					<input type="text" name="search " placeholder="Please type the product you need here" class="big-dog" name="search" required="">
					<button class="btn1"><i class="fa fa-search" aria-hidden="true"></i></button>
				</form>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
	</div>

<div class="w3_navigation">
	<div class="container">
		<nav class="navbar navbar-default">
			<div class="navbar-header navbar-left">
			<%= image_tag "logo_vavimex.png", class: "img-responsive", alt: "Vavimex" %>

				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>

			</div>
			<div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
				<nav class="menu menu--iris">
					<ul class="nav navbar-nav menu__list">
						<li class="menu__item menu__item--current"<%= link_to "Home", root_path, class: "menu__link", "data-turbolinks": false %></a></li>
						<li class="menu__item"><%= link_to "About", root_path(anchor: "about"), "data-turbolinks": false, class: "menu__link" %></li>
						<li class="dropdown menu__item">
							<a href="#" class="dropdown-toggle menu__link" data-toggle="dropdown">Gallery<b class="caret"></b></a>
							<ul class="dropdown-menu agile_short_dropdown">
								<li><%= link_to "RICE HUSK PRODUCT", root_path(anchor: "products"), "data-turbolinks": false %></li>
							</ul>
						</li>
						<li class="menu__item"><%= link_to "Contact", root_path(anchor: "contact"), class: "menu__link", "data-turbolinks": false %></li>
					</ul>
				</nav>
			</div>
		</nav>

	</div>
</div>